"""
Dynamic Footage Requirements Generator — Hermes-driven footage requirement planning.

Replaces the fixed 10 story slots with a dynamic plan generated by Hermes
from the user request, match/event context, story type, emotional arc,
intended duration, narration strategy, and platform.

Each requirement contains the full context needed for discovery and acquisition.
"""

import json
import uuid
from dataclasses import dataclass, asdict, field
from datetime import datetime
from pathlib import Path
from typing import Any, Optional


# The 10 legacy story slots kept as emergency fallback templates
LEGACY_STORY_SLOTS = [
    "opening_pressure",
    "stadium_atmosphere", 
    "player_closeup",
    "critical_attack",
    "goalkeeper_reaction",
    "bench_reaction",
    "crowd_eruption",
    "opposition_disappointment",
    "final_celebration",
    "ending_image"
]

# Story structure templates from emotion-pattern-library
STORY_STRUCTURES = {
    "pain_pressure_comeback_legacy": {
        "phases": ["pain_hook", "past_failure", "pressure_doubt", "comeback_decisive", "legacy_aftermath"],
        "emotional_arc": ["pain", "context", "pressure", "release", "meaning"]
    },
    "doubt_proof_celebration": {
        "phases": ["doubt_criticism", "skill_under_pressure", "opponent_reaction", "validation", "ending"],
        "emotional_arc": ["doubt", "proof", "reaction", "celebration", "closure"]
    },
    "final_chance_failure_ending": {
        "phases": ["setup", "decisive_failure", "player_reaction", "crowd_team_reaction", "respectful_close"],
        "emotional_arc": ["hope", "heartbreak", "reaction", "collective", "meaning"]
    },
    "rivalry_humiliation_revenge": {
        "phases": ["rivalry_setup", "humiliation", "pressure_build", "decisive_answer", "opponent_fan_reaction"],
        "emotional_arc": ["tension", "pain", "pressure", "release", "vindication"]
    },
    "nation_hopes_player_burden": {
        "phases": ["nation_fans", "player_closeup_burden", "match_context", "decisive_moment", "national_reaction"],
        "emotional_arc": ["pride", "burden", "context", "release", "collective_joy"]
    },
    "heroic_failure": {
        "phases": ["team_struggle", "player_response", "repeated_effort", "final_defeat", "lonely_aftermath"],
        "emotional_arc": ["struggle", "heroism", "effort", "defeat", "meaning"]
    },
    "shock_collapse": {
        "phases": ["expectation_setup", "first_crack", "rapid_collapse", "shocked_faces", "aftermath_silence"],
        "emotional_arc": ["expectation", "crack", "collapse", "shock", "silence"]
    }
}


@dataclass
class FootageRequirement:
    """
    A single dynamic footage requirement generated by Hermes.
    
    Each requirement contains everything needed for discovery, acquisition,
    and editorial placement.
    """
    slot_id: str                          # Unique identifier (e.g., "req_pressure_01")
    purpose: str                          # Editorial purpose (e.g., "Establish pre-match tension")
    story_section: str                    # Which story phase this serves
    required_emotion: str                 # Target emotion for this clip
    desired_subject: str                  # Who/what should be in frame
    desired_action: str                   # What should be happening
    visual_type: str                      # closeup | wide | medium | reaction | action | graphic
    priority: int                         # 1=critical, 2=important, 3=supporting, 4=optional
    minimum_clips: int                    # Minimum acceptable clips for this requirement
    search_terms: list[str]               # Primary search queries for discovery
    alternative_terms: list[str]          # Fallback search queries
    optional: bool = False                # Can be dropped if no footage found
    estimated_duration_seconds: float = 5.0  # Target duration in final edit
    story_role: str = "source_clip"       # hook_reference | source_clip | deep_analysis_reference | audio_reference | thumbnail_reference
    platform_considerations: dict = field(default_factory=dict)  # aspect_ratio, safe_zones, etc.
    metadata: dict = field(default_factory=dict)  # Flexible extension
    
    def to_dict(self) -> dict:
        return asdict(self)
    
    @classmethod
    def from_dict(cls, data: dict) -> "FootageRequirement":
        return cls(**data)


@dataclass
class FootageRequirementsPlan:
    """
    Complete footage requirements plan generated by Hermes.
    
    This replaces the fixed 10-slot template with a dynamic, story-specific plan.
    """
    project_id: str
    generated_at: str
    user_request: str
    match_context: dict                   # competition, teams, players, date, etc.
    story_type: str                       # From STORY_STRUCTURES keys
    emotional_arc: list[str]              # Phase-by-phase emotions
    intended_duration_seconds: int
    narration_strategy: str               # narrator | commentary | hybrid | none
    platform: str                         # youtube_longform | youtube_shorts | tiktok | instagram_reels | mixed
    requirements: list[FootageRequirement]
    legacy_fallback_slots: list[str] = field(default_factory=lambda: LEGACY_STORY_SLOTS.copy())
    schema_version: str = "1.0"
    
    def to_dict(self) -> dict:
        data = asdict(self)
        data["requirements"] = [r.to_dict() for r in self.requirements]
        return data
    
    @classmethod
    def from_dict(cls, data: dict) -> "FootageRequirementsPlan":
        reqs = [FootageRequirement.from_dict(r) for r in data.get("requirements", [])]
        data["requirements"] = reqs
        return cls(**data)
    
    def get_requirements_by_section(self, section: str) -> list[FootageRequirement]:
        """Get all requirements for a specific story section."""
        return [r for r in self.requirements if r.story_section == section]
    
    def get_critical_requirements(self) -> list[FootageRequirement]:
        """Get priority 1 (critical) requirements."""
        return [r for r in self.requirements if r.priority == 1]
    
    def get_search_queries(self) -> dict[str, list[str]]:
        """Extract search queries organized by slot_id for discovery engine."""
        queries = {}
        for req in self.requirements:
            queries[req.slot_id] = req.search_terms + req.alternative_terms
        return queries
    
    def validate(self) -> list[str]:
        """Validate the plan and return list of issues (empty if valid)."""
        issues = []
        
        if not self.requirements:
            issues.append("No footage requirements defined")
        
        critical = self.get_critical_requirements()
        if not critical:
            issues.append("No critical (priority 1) requirements defined")
        
        # Check for duplicate slot_ids
        slot_ids = [r.slot_id for r in self.requirements]
        if len(slot_ids) != len(set(slot_ids)):
            issues.append("Duplicate slot_ids found")
        
        # Check each requirement has search terms
        for req in self.requirements:
            if not req.search_terms:
                issues.append(f"Requirement {req.slot_id} has no search terms")
        
        return issues


class FootageRequirementsGenerator:
    """
    Generates dynamic footage requirements from user request via Hermes.
    
    This class provides the Python-side orchestration; the actual creative
    generation happens in Hermes via the football-story-strategy skill.
    """
    
    def __init__(self, hermes_runner=None):
        self.hermes_runner = hermes_runner
    
    def build_hermes_prompt(
        self,
        user_request: str,
        match_context: dict,
        target_emotion: str,
        duration_seconds: int,
        platform: str,
        narration_strategy: str = "hybrid"
    ) -> str:
        """Build the prompt for Hermes to generate footage requirements."""
        
        # Get relevant story structure
        story_structure = self._infer_story_structure(target_emotion, user_request)
        
        prompt = f"""You are the Football Emotion Creative Director. Generate a dynamic footage requirements plan.

USER REQUEST: {user_request}

MATCH/EVENT CONTEXT:
- Competition: {match_context.get('competition', 'Unknown')}
- Teams: {match_context.get('teams', ['Unknown', 'Unknown'])}
- Players: {match_context.get('players', [])}
- Date: {match_context.get('date', 'Unknown')}
- Known key moments: {match_context.get('key_moments', 'Not specified')}

TARGET EMOTION: {target_emotion}
INTENDED DURATION: {duration_seconds} seconds ({duration_seconds/60:.1f} minutes)
PLATFORM: {platform}
NARRATION STRATEGY: {narration_strategy}

STORY STRUCTURE TEMPLATE: {story_structure}
  Phases: {STORY_STRUCTURES.get(story_structure, {}).get('phases', [])}
  Emotional Arc: {STORY_STRUCTURES.get(story_structure, {}).get('emotional_arc', [])}

TASK: Generate a structured footage requirements plan as JSON. Each requirement must contain:

{{
  "slot_id": "unique_id",
  "purpose": "editorial purpose in one sentence",
  "story_section": "which phase of the story structure this serves",
  "required_emotion": "target emotion for this clip",
  "desired_subject": "who/what should be visible",
  "desired_action": "what should be happening",
  "visual_type": "closeup|wide|medium|reaction|action|graphic",
  "priority": 1-4,
  "minimum_clips": 1-3,
  "search_terms": ["primary query 1", "primary query 2"],
  "alternative_terms": ["fallback query 1", "fallback query 2"],
  "optional": false,
  "estimated_duration_seconds": 5.0,
  "story_role": "hook_reference|source_clip|deep_analysis_reference|audio_reference|thumbnail_reference",
  "platform_considerations": {{"aspect_ratio": "16:9", "safe_zones": true}},
  "metadata": {{}}
}}

RULES:
1. Generate 8-15 requirements total (more for longer videos)
2. At least 3 priority-1 (critical) requirements
3. Cover ALL phases of the story structure
4. Search terms must be specific, not generic ("Messi tunnel walk World Cup 2022" not "football player")
5. Include non-English queries for at least 30% of requirements
6. Platform considerations: vertical for Shorts/TikTok, horizontal for longform
7. Story roles: at least 1 hook_reference, 1 audio_reference, 1 thumbnail_reference
8. Each requirement must serve the emotional arc — no filler

OUTPUT: Return ONLY the JSON object matching FootageRequirementsPlan schema.
"""
        return prompt
    
    def _infer_story_structure(self, target_emotion: str, user_request: str) -> str:
        """Map target emotion to story structure."""
        emotion_map = {
            "comeback": "pain_pressure_comeback_legacy",
            "legacy": "pain_pressure_comeback_legacy",
            "redemption": "pain_pressure_comeback_legacy",
            "heartbreak": "final_chance_failure_ending",
            "last_chance": "final_chance_failure_ending",
            "revenge": "rivalry_humiliation_revenge",
            "response": "rivalry_humiliation_revenge",
            "national_pride": "nation_hopes_player_burden",
            "world_cup": "nation_hopes_player_burden",
            "heroic_failure": "heroic_failure",
            "brilliant_losers": "heroic_failure",
            "collapse": "shock_collapse",
            "humiliation": "shock_collapse",
            "doubt": "doubt_proof_celebration",
            "proof": "doubt_proof_celebration",
            "skill": "doubt_proof_celebration",
            "dominance": "doubt_proof_celebration",
        }
        
        request_lower = user_request.lower()
        for keyword, structure in emotion_map.items():
            if keyword in request_lower or keyword in target_emotion.lower():
                return structure
        
        # Default to most versatile structure
        return "pain_pressure_comeback_legacy"
    
    def _extract_json(self, text: str) -> str:
        """Extract JSON object from text that may contain markdown or extra content."""
        # Try to find JSON block
        if "```json" in text:
            start = text.find("```json") + 7
            end = text.find("```", start)
            return text[start:end].strip()
        elif "```" in text:
            start = text.find("```") + 3
            end = text.find("```", start)
            return text[start:end].strip()
        
        # Try to find first { and last }
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            return text[start:end+1]
        
        raise ValueError("No JSON found in Hermes output")
    
    def parse_hermes_output(self, hermes_output: str) -> FootageRequirementsPlan:
        """Parse Hermes JSON output into FootageRequirementsPlan."""
        json_str = self._extract_json(hermes_output)
        data = json.loads(json_str)
        return FootageRequirementsPlan.from_dict(data)
    
    def generate_fallback_plan(
        self,
        user_request: str,
        match_context: dict,
        target_emotion: str,
        duration_seconds: int,
        platform: str
    ) -> FootageRequirementsPlan:
        """
        Generate a fallback plan using legacy slots when Hermes is unavailable.
        
        This provides the 10 legacy slots as a template, adapted to the request.
        """
        story_structure = self._infer_story_structure(target_emotion, user_request)
        phases = STORY_STRUCTURES.get(story_structure, {}).get("phases", [])
        
        # Build requirements from legacy slots, mapped to story phases
        requirements = []
        
        # Map legacy slots to story phases
        slot_to_phase = {
            "opening_pressure": phases[0] if len(phases) > 0 else "hook",
            "stadium_atmosphere": phases[0] if len(phases) > 0 else "hook",
            "player_closeup": phases[1] if len(phases) > 1 else "context",
            "critical_attack": phases[2] if len(phases) > 2 else "pressure",
            "goalkeeper_reaction": phases[2] if len(phases) > 2 else "pressure",
            "bench_reaction": phases[3] if len(phases) > 3 else "reversal",
            "crowd_eruption": phases[3] if len(phases) > 3 else "climax",
            "opposition_disappointment": phases[3] if len(phases) > 3 else "aftermath",
            "final_celebration": phases[4] if len(phases) > 4 else "outro",
            "ending_image": phases[4] if len(phases) > 4 else "outro",
        }
        
        # Emotion mapping per slot
        slot_emotions = {
            "opening_pressure": "tension",
            "stadium_atmosphere": "anticipation",
            "player_closeup": "focus",
            "critical_attack": "intensity",
            "goalkeeper_reaction": "drama",
            "bench_reaction": "tension",
            "crowd_eruption": "release",
            "opposition_disappointment": "heartbreak",
            "final_celebration": "triumph",
            "ending_image": "reflection",
        }
        
        # Visual types per slot
        slot_visual = {
            "opening_pressure": "wide",
            "stadium_atmosphere": "wide",
            "player_closeup": "closeup",
            "critical_attack": "action",
            "goalkeeper_reaction": "reaction",
            "bench_reaction": "reaction",
            "crowd_eruption": "wide",
            "opposition_disappointment": "reaction",
            "final_celebration": "action",
            "ending_image": "wide",
        }
        
        # Priorities - first and last are critical
        slot_priority = {
            "opening_pressure": 1,
            "stadium_atmosphere": 2,
            "player_closeup": 1,
            "critical_attack": 2,
            "goalkeeper_reaction": 3,
            "bench_reaction": 3,
            "crowd_eruption": 1,
            "opposition_disappointment": 2,
            "final_celebration": 1,
            "ending_image": 2,
        }
        
        players = match_context.get("players", [])
        teams = match_context.get("teams", [])
        competition = match_context.get("competition", "tournament")
        
        # Default fallbacks for empty lists
        first_player = players[0] if players else "player"
        first_team = teams[0] if teams else "team"
        
        for slot in LEGACY_STORY_SLOTS:
            req = FootageRequirement(
                slot_id=slot,
                purpose=f"Legacy fallback: {slot.replace('_', ' ')} for {target_emotion} story",
                story_section=slot_to_phase.get(slot, "unknown"),
                required_emotion=slot_emotions.get(slot, target_emotion),
                desired_subject=f"{first_player} {first_team}" if players else first_team,
                desired_action=slot.replace("_", " "),
                visual_type=slot_visual.get(slot, "medium"),
                priority=slot_priority.get(slot, 3),
                minimum_clips=1,
                search_terms=self._build_legacy_queries(slot, players, teams, competition),
                alternative_terms=self._build_legacy_alt_queries(slot, players, teams, competition),
                optional=(slot_priority.get(slot, 3) >= 3),
                estimated_duration_seconds=duration_seconds / 10,
                story_role="hook_reference" if slot == "opening_pressure" else "source_clip",
                platform_considerations={"aspect_ratio": "9:16" if platform in ["youtube_shorts", "tiktok", "instagram_reels"] else "16:9"},
                metadata={"legacy_fallback": True, "original_slot": slot}
            )
            requirements.append(req)
        
        return FootageRequirementsPlan(
            project_id=f"fallback_{uuid.uuid4().hex[:8]}",
            generated_at=datetime.utcnow().isoformat(),
            user_request=user_request,
            match_context=match_context,
            story_type=story_structure,
            emotional_arc=STORY_STRUCTURES.get(story_structure, {}).get("emotional_arc", []),
            intended_duration_seconds=duration_seconds,
            narration_strategy="hybrid",
            platform=platform,
            requirements=requirements
        )
    
    def _build_legacy_queries(self, slot: str, players: list[str], teams: list[str], competition: str) -> list[str]:
        """Build search queries for legacy slot (5 styles per architecture)."""
        player = players[0] if players else ""
        team = teams[0] if teams else ""
        
        templates = {
            "opening_pressure": [
                f"{player} {team} {competition} pressure tension build up",
                f"{player} nervous before {competition} final",
                f"football pressure moment {player} {competition} cinematic",
                f"official broadcast {team} {competition} tunnel walk atmosphere",
                f"{player} {competition} pression tension avant match"
            ],
            "stadium_atmosphere": [
                f"{team} {competition} stadium atmosphere crowd chanting",
                f"{competition} final stadium full roar atmosphere",
                f"football stadium atmosphere cinematic {team} fans",
                f"broadcast {team} stadium atmosphere pre match",
                f"{team} estadio ambiente aficionados {competition}"
            ],
            "player_closeup": [
                f"{player} close up face reaction {competition}",
                f"{player} emotional face tears joy {competition}",
                f"cinematic football player portrait {player} {competition}",
                f"official {player} close up {competition} broadcast quality",
                f"{player} primer plano cara emocion {competition}"
            ],
            "critical_attack": [
                f"{player} {team} attack chance {competition} goal",
                f"{player} missed chance {competition} heartbreak",
                f"football attacking move {team} {competition} tactical",
                f"broadcast {team} dangerous attack {competition} build up",
                f"{player} ataque oportunidad gol {competition}"
            ],
            "goalkeeper_reaction": [
                f"goalkeeper save reaction {competition} {team}",
                f"penalty save goalkeeper {competition} dramatic",
                f"football goalkeeper dive save {competition} close up",
                f"official goalkeeper {competition} penalty shootout reaction",
                f"portero atajada reaccion {competition} penalti"
            ],
            "bench_reaction": [
                f"bench reaction {team} {competition} coach manager",
                f"substitute bench celebration {team} {competition}",
                f"football manager reaction touchline {competition} bench",
                f"broadcast coach bench reaction {competition} {team}",
                f"banquillo reaccion entrenador {team} {competition}"
            ],
            "crowd_eruption": [
                f"crowd eruption celebration {team} {competition} goal",
                f"fans go wild {player} goal {competition} stadium",
                f"football crowd celebration {team} {competition} eruption",
                f"broadcast stadium eruption {competition} winning goal",
                f"aficion celebracion gol {team} {competition} estadio"
            ],
            "opposition_disappointment": [
                f"opposition disappointed {competition} {team} defeat",
                f"heartbreak tears {team} opponent {competition} loss",
                f"football defeat reaction opposition {competition} devastated",
                f"broadcast losing team reaction {competition} final whistle",
                f"derrota desconsuelo llanto {team} {competition}"
            ],
            "final_celebration": [
                f"{player} lifting trophy {competition} celebration",
                f"{team} champions {competition} trophy lift party",
                f"football championship celebration {team} {competition} winners",
                f"official trophy presentation {team} {competition} champions",
                f"{player} levanta trofeo campeon {competition} celebracion"
            ],
            "ending_image": [
                f"final whistle {competition} {team} empty stadium silence",
                f"{player} walking away {competition} reflection",
                f"football poetic ending {competition} final image cinematic",
                f"broadcast post match empty stadium {competition} aftermath",
                f"silencio estadio final {competition} {team} reflexion"
            ],
        }
        
        return templates.get(slot, [f"{player} {team} {competition} {slot}"])
    
    def _build_legacy_alt_queries(self, slot: str, players: list[str], teams: list[str], competition: str) -> list[str]:
        """Build alternative/fallback queries."""
        player = players[0] if players else ""
        team = teams[0] if teams else ""
        
        alt_templates = {
            "opening_pressure": [f"{team} tunnel walk {competition}", f"pre match {competition} atmosphere"],
            "stadium_atmosphere": [f"{team} fans chanting {competition}", f"stadium roar {competition}"],
            "player_closeup": [f"{player} face {competition}", f"football player close up {competition}"],
            "critical_attack": [f"{team} attack {competition}", f"goal chance {competition}"],
            "goalkeeper_reaction": [f"goalkeeper save {competition}", f"penalty shootout {competition} keeper"],
            "bench_reaction": [f"coach reaction {competition}", f"manager touchline {competition}"],
            "crowd_eruption": [f"crowd celebration {competition}", f"fans celebrating {team} goal"],
            "opposition_disappointment": [f"losing team reaction {competition}", f"defeat reaction {competition}"],
            "final_celebration": [f"{team} trophy lift", f"champions celebration {competition}"],
            "ending_image": [f"post match {competition} empty stadium", f"final whistle {competition}"],
        }
        
        return alt_templates.get(slot, [f"{team} {competition} football"])


def save_footage_requirements(plan: FootageRequirementsPlan, output_path: Path) -> Path:
    """Save footage requirements plan to JSON file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(plan.to_dict(), indent=2))
    return output_path


def load_footage_requirements(input_path: Path) -> FootageRequirementsPlan:
    """Load footage requirements plan from JSON file."""
    data = json.loads(input_path.read_text())
    return FootageRequirementsPlan.from_dict(data)


# CLI for testing
if __name__ == "__main__":
    import sys
    
    generator = FootageRequirementsGenerator()
    
    # Test fallback generation
    print("Testing fallback footage requirements generation...")
    
    plan = generator.generate_fallback_plan(
        user_request="Messi World Cup 2022 triumph story",
        match_context={
            "competition": "World Cup 2022",
            "teams": ["Argentina", "France"],
            "players": ["Messi", "Mbappe"],
            "date": "2022-12-18",
            "key_moments": "Messi goals, penalty shootout, trophy lift"
        },
        target_emotion="triumph",
        duration_seconds=180,
        platform="youtube_longform"
    )
    
    print(f"Project ID: {plan.project_id}")
    print(f"Story type: {plan.story_type}")
    print(f"Duration: {plan.intended_duration_seconds}s")
    print(f"Platform: {plan.platform}")
    print(f"Requirements: {len(plan.requirements)}")
    
    for req in plan.requirements:
        print(f"\n  {req.slot_id} (priority {req.priority})")
        print(f"    Purpose: {req.purpose}")
        print(f"    Section: {req.story_section}")
        print(f"    Emotion: {req.required_emotion}")
        print(f"    Subject: {req.desired_subject}")
        print(f"    Action: {req.desired_action}")
        print(f"    Visual: {req.visual_type}")
        print(f"    Min clips: {req.minimum_clips}")
        print(f"    Search terms: {req.search_terms[:2]}...")
        print(f"    Alt terms: {req.alternative_terms[:2]}...")
        print(f"    Optional: {req.optional}")
    
    # Validate
    issues = plan.validate()
    if issues:
        print(f"\nValidation issues: {issues}")
    else:
        print("\n✓ Plan validates successfully")
    
    # Save test output
    output_path = Path("/tmp/football_emotion/footage_requirements_test.json")
    save_footage_requirements(plan, output_path)
    print(f"\nSaved to: {output_path}")